-- CreateTable
CREATE TABLE "TrackEvent" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ts" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "data" TEXT NOT NULL
);
